export const Schedules = {
  "جدول الكبار بالعربي": [
    {
      day: "الخميس",
      events: [
        "الوصول والتسجيل: 6:00",
        "العشاء: 7:00",
        "ترانيم: 8:30 – 9:15",
        "الخدمة الافتتاحية: 9:15 – 10:15",
      ],
    },
    {
      day: "الجمعة والسبت",
      events: [
        "التأمل والصلاة: 7:00 – 7:30",
        "الفطور: 7:30 – 8:30",
        "مواضيع تطبيقية: 9:00 – 10:00",
        "ترانيم: 10:30 – 11:15",
        "الخدمة الصباحية: 11:15 – 12:15",
        "الغذاء: 12:30 – 1:30",
        "استراحة: 1:30 – 4:00",
        "مواضيع خاصة (ورشات عمل): 4:00 – 5:15",
        "العشاء: 5:30 – 6:30",
        "ترانيم: 7:30 – 8:15",
        "الخدمة المسائية: 8:15 – 9:15",
        "سهرة روحية: 9:15 – 11:00",
        "اطفاء الانوار: 11:30 مساءً",
      ],
    },
    {
      day: "الأحد",
      events: [
        "التأمل والصلاة: 7:00 – 7:30",
        "الفطور: 7:30 – 8:30",
        "ترانيم: 9:15 – 10:00",
        "الخدمة الختامية مع خدمة التكريس: 10:00 – 11:00",
      ],
    },
  ],
  "English Adults": [
    {
      day: "Thursday 7/3",
      events: [
        "6PM: Registration",
        "7PM: Dinner - Cougar Den",
        "8:30PM - 9:15PM: Praise and Worship - Band Room",
        "9:15PM - 10PM: First Session (Leaders: Pastor Adam / Pastor Khalaf)",
        "10PM - 11:30PM: Bonfire & Dunckel Gym",
      ],
    },
    {
      day: "Friday 7/4",
      events: [
        "7:30AM - 8:30AM: Breakfast - Cougar Den",
        "8:45AM - 9:30AM: Praise and Worship",
        "9:45AM - 10:30AM: Morning Session (Leaders: Pastor Adam / Pastor Khalaf)",
        "10:45AM - 11:45AM: Capture the Flag (Leaders: Asher & Andrew)",
        "12:30PM - 1:30PM: Lunch - Cougar Den",
        "1:30PM - 4PM: Free Time",
        "5:30PM - 6:30PM: Dinner - Cougar Den",
        "7:00PM - 7:45PM: Praise and Worship",
        "8:00PM - 9:00PM: Evening Session (Leaders: Pastor Adam / Pastor Khalaf)",
        "9:00PM - 11:30PM: Bonfire & Dunckel Gym",
      ],
    },
    {
      day: "Saturday 7/5",
      events: [
        "7:30AM - 8:30AM: Breakfast - Cafeteria",
        "8:45AM - 9:30AM: Praise and Worship",
        "9:45AM - 10:30AM: Morning Session (Leaders: Pastor Adam / Pastor Khalaf)",
        "10:45AM - 11:45AM: Hunger Games Activity (Leader: Rabi)",
        "12:30PM - 1:30PM: Lunch - Cafeteria",
        "1:30PM - 4PM: Free Time - Dunckel Gym 2-5",
        "5:30PM - 6:30PM: Dinner - Cafeteria",
        "7:00PM - 7:45PM: Praise and Worship",
        "8:00PM - 9:00PM: Evening Session (Leaders: Pastor Adam / Pastor Khalaf)",
        "9:15PM - 11PM: Saturday Night Sahra (All Together)",
      ],
    },
    {
      day: "Sunday 7/6",
      events: [
        "7:30AM - 8:30AM: Breakfast - Cafeteria",
        "8:45AM - 9:30AM: Praise and Worship - Band Room",
        "10AM: Morning Session (Leaders: Pastor Adam / Pastor Khalaf)",
        "12PM: Check Out",
      ],
    },
  ],
  "Junior High": [
    {
      day: "Thursday 7/3",
      events: [
        "6PM: Registration",
        "7PM: Dinner - Cougar Den",
        "8:30PM - 9:15PM: Praise and Worship - Band Room",
        "9:15PM - 10PM: First Session (Leaders: Pastor Adam / Pastor Khalaf)",
        "10pm - 11:30pm: Bonfire and Dunckel Gym",
      ],
    },
    {
      day: "Friday 7/4",
      events: [
        "7:30AM - 8:30AM: Breakfast - Cougar Den",
        "8:45AM - 9:30AM: Praise and Worship",
        "9:45AM - 10:30AM: Morning Session (Leader: Manny)",
        "10:45AM - 11:45AM: Capture the Flag (Leaders: Asher & Andrew)",
        "12:30PM - 1:30PM: Lunch - Cougar Den",
        "1:30PM - 4PM: Free Time",
        "5:30PM - 6:30PM: Dinner - Cougar Den",
        "7:00PM - 7:45PM: Praise and Worship",
        "8:00PM - 9:00PM: Evening Session (Leader: Erica)",
        "9:00PM - 11:30PM: Bonfire & Dunckel Gym",
      ],
    },
    {
      day: "Saturday 7/5",
      events: [
        "7:30AM - 8:30AM: Breakfast - Cafeteria",
        "8:45AM - 9:30AM: Praise and Worship",
        "9:45AM - 10:30AM: Morning Session (Leader: Marianne)",
        "10:45AM - 11:45AM: Hunger Games Activity (Leader: Rabi)",
        "12:30PM - 1:30PM: Lunch - Cafeteria",
        "1:30PM - 4PM: Free Time - Dunckel Gym 2-5",
        "5:30PM - 6:30PM: Dinner - Cafeteria",
        "7:00PM - 7:45PM: Praise and Worship",
        "8:00PM - 9:00PM: Evening Session (Leader: Danny Hindi)",
        "9:15PM - 11PM: Saturday Night Sahra (All Together)",
      ],
    },
    {
      day: "Sunday 7/6",
      events: [
        "7:30AM - 8:30AM: Breakfast - Cafeteria",
        "8:45AM - 9:30AM: Praise and Worship - Band Room",
        "10AM: Morning Session (Leader: Manny)",
        "12PM: Check Out",
      ],
    },
  ],

  "Pre-K to 2nd": [
    {
      day: "Thursday 7/3",
      events: [
        "6PM: Registration",
        "7PM: Dinner - Cougar Den",
        "8:30PM - 9:15PM: Praise and Worship - Room 110 (Leader: Nada Yousif)",
        "9:15PM - 10PM: First Session - Room 110 (Leader: Mary Kakish)",
        "Bonfire and Dunckel Gym: Open til 11:30PM",
      ],
    },
    {
      day: "Friday 7/4",
      events: [
        "7:30AM - 8:30AM: Breakfast - Cougar Den",
        "8:45AM - 9:30AM: Worship (Leader: Rebecca)",
        "9:45AM - 10:30AM: Morning Session (Leaders: Wrein & Sandy)",
        "10:45AM - 11:45AM: Activity/Craft (Leaders: Wrein & Sandy)",
        "12:30PM - 1:30PM: Lunch - Cougar Den",
        "1:30PM - 4PM: Free Time",
        "5:30PM - 6:30PM: Dinner - Cougar Den",
        "7:00PM - 7:45PM: Evening Session (Leader: Shams)",
        "8:00PM - 9:00PM: Activity/Craft (Leader: Elvira)",
        "9:00PM - 11:30PM: Bonfire & Dunckel Gym",
      ],
    },
    {
      day: "Saturday 7/5",
      events: [
        "7:30AM - 8:30AM: Breakfast - Cafeteria",
        "8:45AM - 9:30AM: Worship (Leader: Nana)",
        "9:45AM - 10:30AM: Morning Session (Leader: Nada)",
        "10:45AM - 11:45AM: Activity/Craft (Leader: Elvira)",
        "12:30PM - 1:30PM: Lunch - Cafeteria",
        "1:30PM - 4PM: Free Time - Dunckel Gym 2-5",
        "5:30PM - 6:30PM: Dinner - Cafeteria",
        "7:00PM - 7:45PM: Evening Session (Leader: Laila)",
        "8:00PM - 9:00PM: Activity/Craft (Leader: Mona)",
        "9:15PM - 11PM: Saturday Night Sahra (All Together)",
      ],
    },
    {
      day: "Sunday 7/6",
      events: [
        "7:30AM - 8:30AM: Breakfast - Cafeteria",
        "8:45AM - 9:30AM: Worship (Leader: Lillian)",
        "10AM: Morning Session (Leader: Nana)",
        "12PM: Check Out",
      ],
    },
  ],
};
